version: 2.1

jobs:
  build:
    docker: # Executor タイプです。他に machine、macOS という実行タイプを指定できます
      - image: circleci/node:10.15.1 # プライマリコンテナです。このなかでジョブコマンドが実行されます
    steps:
      - checkout # プロジェクトのディレクトリにあるコードをチェックアウトします
      - run: npm install
      - run: npm run dev
  deploy:
    machine: true
    steps:
      - run:  wget -qO- https://cli-assets.heroku.com/install-ubuntu.sh | sh
      - run:  bash .circleci/setup-heroku.sh
      - add_ssh_keys:
          fingerprints:
          - "fe:49:16:7f:3e:33:f7:39:8a:51:5f:62:ed:47:a0:33"
      - deploy:
          name: heroku deploy
          command: |
              if [ "${CIRCLE_BRANCH}" == "master" ]; then
                  git push heroku master
              fi 
      
workflows:
    version: 2.1
    build_and_deploy:
        jobs:
          - build
          - hold-deploy:
              type: approval
              requires:
                - build
          - deploy:
              requires:
                - hold-deploy
              filters:
                branches:
                  only: master