version: 2.1

jobs:
  build:
    docker: # Executor タイプです。他に machine、macOS という実行タイプを指定できます
      - image: circleci/node:10.15.1 # プライマリコンテナです。このなかでジョブコマンドが実行されます
    steps:
      - checkout # プロジェクトのディレクトリにあるコードをチェックアウトします
      - run: npm run dev
  notice:
    machine: true
    steps:
      - run: echo "build success!!"
      
workflows:
    build workflow:
        jobs:
          - build
          - notice